name: Update Kubernetes Manifests

on:
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if file exists
        run: |
          test -f k8s/deployment.yaml || (echo "File not found!" && exit 1)

      - name: Update image tag
        run: |
          sed -i 's|image: .*|image: darksp1der/characters-fate:slim|' k8s/deployment.yaml

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag" || echo "No changes to commit"
          git push origin master
